version: "3"

services:
  web:
    image: whizzplayer:web
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        VERSION_CODE: dev docker
    ports:
      - 3000:3000
  api:
    image: whizzplayer:api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        VERSION_CODE: dev docker
    env_file:
      - ./api/.docker.env
    volumes:
      - "./uploads/:/uploads"
    ports:
      - 4000:4000
  back:
    image: whizzplayer:back
    build:
      context: ./back
      dockerfile: ./Dockerfile
      args:
        VERSION_CODE: dev docker
    volumes:
      - "./uploads/:/uploads"
    devices:
      - "/dev/snd"
    ports:
      - 5000:5000
  proxy:
    image: whizzplayer:proxy
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
      args:
        VERSION_CODE: dev docker
    ports:
      - 80:80
