version: "3"

services:
  db:
    image: jsurf/rpi-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: UTC
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: nathanrignall/whizzplayer:web-alpha
    restart: always
  back:
    image: nathanrignall/whizzplayer:back-alpha
    restart: always
    volumes:
      - "./uploads/:/uploads"
    devices:
      - "/dev/snd"
  api:
    image: nathanrignall/whizzplayer:api-alpha
    restart: always
    volumes:
      - "./uploads/:/uploads"
      - "./config/default.json:/default.json"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASS: password
  proxy:
    image: nathanrignall/whizzplayer:proxy-alpha
    restart: always
    ports:
      - 80:80
