CREATE TABLE Cues (
	CueID BIGINT NOT NULL UNIQUE,
	CueName varchar(255) NOT NULL,
	TrackID BIGINT NOT NULL,
	PlayTime DATETIME NOT NULL,
	Repeats BOOLEAN NOT NULL DEFAULT False,
	RepeatMonday BOOLEAN DEFAULT False,
	RepeatTuesday BOOLEAN DEFAULT False,
	RepeatWednesday BOOLEAN DEFAULT False,
	RepeatThursday BOOLEAN DEFAULT False,
	RepeatFriday BOOLEAN DEFAULT False,
	RepeatSaturday BOOLEAN DEFAULT False,
	RepeatSunday BOOLEAN DEFAULT False,
	Enabled BOOLEAN NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (CueID),
    CONSTRAINT fk_Cues_Tracks_TrackID FOREIGN KEY (TrackID) REFERENCES Tracks(TrackID) ON DELETE CASCADE
);

CREATE TABLE Tracks (
	TrackID BIGINT NOT NULL UNIQUE,
    TrackName varchar(255) NOT NULL,
	Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TrackID)
);

CREATE TABLE Users (
	UserID BIGINT NOT NULL UNIQUE,
	Email varchar(255) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
	DisplayName varchar(255) NOT NULL,
	Password varchar(2048) NOT NULL,
    Access int(1) NOT NULL,
	Enabled BOOLEAN NOT NULL DEFAULT True,
	Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (UserID)
);

CREATE TABLE SystemLog (
	LogID int NOT NULL UNIQUE AUTO_INCREMENT,
	UserDisplayName varchar(255) NOT NULL,
	Details varchar(2048) NOT NULL,
	Error BOOLEAN NOT NULL,
	Time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (LogID)
);

CREATE TABLE PlayLog (
	LogID int NOT NULL UNIQUE AUTO_INCREMENT,
	TrackDisplayName varchar(255) NOT NULL,
	Details varchar(2048) NOT NULL,
	Time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (LogID)
);