name: Proxy Alpha Image Build

on:
  push:
    tags:
      - "v*.*.*-alpha.*"
    path:
      - "proxy/**"

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          context: ./proxy/
          file: ./proxy/Dockerfile
          build-args: VERSION_CODE=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: nathanrignall/whizzplayer:proxy-alpha,nathanrignall/whizzplayer:proxy-${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=nathanrignall/whizzplayer:proxy-alpha
          cache-to: type=inline
