name: Full Alpha Image Build

on:
  push:
    tags:
      - "v*.*.*-alpha.*"

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: ./web/
          file: ./web/Dockerfile
          build-args: VERSION_CODE=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: nathanrignall/whizzplayer:web-alpha,nathanrignall/whizzplayer:web-${{ steps.get_version.outputs.VERSION }}
      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          file: ./api/Dockerfile
          build-args: VERSION_CODE=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: nathanrignall/whizzplayer:api-alpha,nathanrignall/whizzplayer:api-${{ steps.get_version.outputs.VERSION }}
      - name: Build and push back
        uses: docker/build-push-action@v2
        with:
          context: ./back/
          file: ./back/Dockerfile
          build-args: VERSION_CODE=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: nathanrignall/whizzplayer:back-alpha,nathanrignall/whizzplayer:back-${{ steps.get_version.outputs.VERSION }}
      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          context: ./proxy/
          file: ./proxy/Dockerfile
          build-args: VERSION_CODE=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: nathanrignall/whizzplayer:proxy-alpha,nathanrignall/whizzplayer:proxy-${{ steps.get_version.outputs.VERSION }}
